kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: godep-tip
  namespace: godep
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - tip.godep.org
    secretName: godep-tip-tls
  rules:
  - host: tip.godep.org
    http:
      paths:
      - backend:
          serviceName: godep-tip
          servicePort: http
